### ISSUE TITLE
support for time_precision: 's'

### ISSUE THREAD

**Issue by smtlaissezfaire** [palkan/influxer#39]
The driver supports different time precisions, but influxer doesn't seem to.  Here's what I need to do in my code to get the right times:

```ruby
  def self.convert_time(time)
    time.to_i * 1_000_000_000 # shouldn't need this?
  end

  scope :between, lambda { |time1, time2|
    where(time: convert_time(time1)..convert_time(time2))
  }

  scope :at_time, lambda { |time|
    where("time <= #{convert_time(time)}")
  }
```

**Comment by smtlaissezfaire** [comment]
My yaml file, for reference:

```yaml
development:
  # database name
  database: 'price_data'
  # influxdb api endpoint
  host: 'localhost'
  port: 8086

  # influxdb user name and password (plain)
  # Please, beware of using root user as API user in production
  username: root
  password: root
  time_precision: 's'
```
